inherit_from: .rubocop_todo.yml

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 110

Lint/HandleExceptions:
  Exclude:
    - rakelib/*.rake
    - spec/spec_helper.rb

Style/SingleLineMethods:
  Exclude:
    - spec/spec_helper.rb
